---
title: "Building a Chat Analyzer app - Part 1"
description: |
  A workflow on how I plan to build this project 
author:
  - name: Emmanuel Ugochukwu
    url: https://github.com/emmanuelugo
base_url: https://dairy-of-an-analyst.netlify.app/
date: 02-07-2022
preview: text-analytics.png
output: 
  distill::distill_article:
    toc: true
    toc_depth: 4
twitter:
  site: "@emm_aguila"
  creator: "@emm_aguila"
categories:
  - NLP
  - Shiny
  - Text Analytics
  - WhatsApp series
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hello 👋

In this post, I go over my plans and ideas on a new project I am embarking on, **A Whatsapp Chat Analyzer**. It is a fun app where the user uploads their chat history and they are filled with fun fact information about their chats.

The number of features that would be in this app hasn't been decided yet but with what I have currently, it should be a fun app. I did a little social experiment with friends and found out how interesting this project would be. Simply telling friends that they have sent **X** amount of messages over a particular period or they use a particular word all the time or some little fun fact can put a smile on their face. In turn, this project would solidify my understanding on Text Analytics and improve my R Shiny skills.

Let's go over some of the features of the app, shall we?

## Features

### Chat Summary Feature

This answers the following questions;

1.  Total number of messages sent.
2.  Total number of users.
3.  Most active user (*by number of text sent)*
4.  User with the highest average length of text.
5.  The least active user (*by number of text sent)*.
6.  The user who uses a lot of Emojis 😅

Plots that would be generated in here would include a plot of the (20) most active users by number of text sent and a plot of the top users with highest average text length.

### Wordcloud and Sentiment Analysis Feature

Here, I plan on grouping text into Happy and Sad sentiments and displaying them with wordclouds and also perform a sentiment trend analysis since there would be a date column.

### Word Association Feature

This would group words together so we can understand how some words are connected. A network graph would be used to display the result.

### Comparison Feature

This feature would drill down to a particular person or group of people and would highlight the following:

1.  Unique words for each user(s).
2.  Activity Status: Average chat length, Number of messages sent, Ranking activity level by some time variables.
3.  Wordcloud to display most used words.
4.  Lexical Diversity.
5.  Sentiments.
6.  A feature to download these analysis.

### Extras

Another fun features to implement would be:

1.  When a user enters a word, the app returns a plot of the people who has used that word the most and also a popularity trend and the total number of times that word was used.

With these few ideas, the app should serve as a good data science project. I gave myself a deadline of 2 months to complete the app and I will try my best to beat that time.

I will be writing more blogs covering the entire process.

See you soon!

❤️